### ISSUE TITLE
Failed to execute the command sent

### ISSUE THREAD

**Issue by CarmeloCampos** [scottie/telegram-altcoin-wallet#3]
User command in the bot: `/send 10 WcLPKQ5HNwAM4qMEozyAzA6h7DmHpUYaSo
`

Dialogue of the console:  `496499134 [object Object]: /send 10 WcLPKQ5HNwAM4qMEozyAzA6h7DmHpUYaSo
http://explorer.wolfclover.com:3333/ext/getbalance/WVqkkZfrAms2AULgR4LAVE77CHXpbwd5MV/
BALANCE: 100.16509582
Balance: 100.16509582
Amount: 10
{ amount: '10', address: 'WcLPKQ5HNwAM4qMEozyAzA6h7DmHpUYaSo' }
{ RpcError: value is type str, expected real
    at getRpcResult (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/altcoin-rpc/dist/src/parser.js:39:11)
    at Client.rpc (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/altcoin-rpc/dist/src/parser.js:82:14)
    at Client.tryCatcher (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/wolfclover_coin/telegram-altcoin-wallet/node_modules/request/request.js:1085:12)
  message: 'value is type str, expected real',
  code: -1,
  name: 'RpcError' }`

Response from the bot to the user: Not enough balance...

**Comment by CarmeloCampos** [comment]
¿?
